version: '3'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - 3310:3310
    environment:
      MYSQL_ROOT_PASSWORD: 'mypassword'
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: 'mypassword'

  jenkins_python:
    image: lucafelipe/jenkins-python-flask:latest
    container_name: jenkins-python
    environment:
      - JENKINS_HOME=/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_data:/var/jenkins_home

volumes:
  mysql_data:
  redis_data:
  dependencies:
