 # docker-compose.yaml
  version: '3.8'
  services:
    jenkins_python:
      image: Henriques100/Jenkins_Python_S107
      container_name: jenkins
      privileged: true
      user: root
      ports:
       - 5000:5000
      volumes:
        - ./jenkins_compose/jenkins_configuration:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock