version: '3.8'

services:
  jenkins_python:
    image: Henriques100/Jenkins_Python_S107
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 5000:5000
    volumes:
      - ./jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  mysql_db:
    build:
      context: ./path/to/your/sql/dockerfile/directory
      dockerfile: Dockerfile-mysql 
    container_name: mysql-db
    ports:
      - 3306:3306  
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data_volume:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - 6379:6379

  app:
    build:
      context: ./my-flask-app
    container_name: flask-app
    ports:
      - 8080:5000
    depends_on:
      - mysql_db
      - redis

volumes:
  mysql_data_volume:
