version: '3'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: mypassword
  jenkins_python:
    image: lucafelipe/jenkins-python-flask:latest
    container_name: jenkins-python
    environment:
      JENKINS_HOME: /var/jenkins_home
    ports:
      - 8090:8090
    volumes:
      - ./jenkins_data:/var/jenkins_home
    command: ["venv/bin/python", "/app/appFlask.py"]
    depends_on:
      - postgres_db
      - redis

volumes:
  postgres_data:
  redis_data:
