pipeline {
    agent {
        label 'ubuntu'
    }
    options {
        skipDefaultCheckout()
    }
    stages {
        stage('Set up Python') {
            steps {
                script {
                    sh 'apt-get update && apt-get install -y python3'
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    sh 'echo "Building..."'
                    sh 'python --version'
                    sh 'ls'
                    sh 'cd Jenkins_Python_S107/flask/requirements/.'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh 'echo "Testing..."'
                    sh 'python -m pip install --upgrade pip'
                    sh 'pip install asgiref greenlet python-dotenv'
                    sh 'cd Jenkins_Python_S107/flask'
                    sh 'pytest'
                    archiveArtifacts 'Jenkins_Python_S107/flask/flash/tests'

                }
            }
        }
        stage('Notifications') {
            steps {
                script {
                    sh 'echo "Notifications..."'
                    sh 'echo "Enviando e-mail para luca.felipe@ges.inatel.br..."'
                    sh 'echo "Enviando mensagem para o canal Slack..."'
                }
            }
        }
    }
}
