pipeline {
    agent {
        label 'ubuntu'
    }
   
    stages {
        stage('Build') {
            steps {
                script {
                    sh 'echo "Building..."'
                    sh 'cd Jenkins_Python_S107/flask/requirements/ && ls *.txt'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh 'echo "Testing..."'
                    sh 'cd Jenkins_Python_S107/flask'
                    sh 'pytest'
                    archiveArtifacts 'Jenkins_Python_S107/flask/flash/tests'

                }
            }
        }

        stage('Notifications') {
            steps {
                script {
                    sh 'echo "Notificação"'
                    sh 'echo "Enviando e-mail para luca.felipe@ges.inatel.br..."'
                    sh 'echo "Enviando mensagem para o canal Slack..."'
                }
            }
        }
    }
}
